### ISSUE TITLE
Console does not display in I.E 8

### ISSUE THREAD

**Issue by feanz** [lukencode/NetBash#17]
There is an issue with the console display in I.E. 8.

Display: none is set for the coneol-results class.  If you remove this there is then display issues with the background color which uses rgb transparency with no fall-back colour.  I've added the fallbacks to the less file submitted it.

**Comment by lukencode** [comment]
Can you confirm this is still the case with the new release?

**Comment by feanz** [comment]
new release fixes issue

On 16 January 2012 03:34, Luke Lowrey <
reply@reply.github.com

> wrote:
> 
> Can you confirm this is still the case with the new release?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/lukencode/NetBash/issues/17#issuecomment-3505846

## 

Regards

Richard Forrest

**Comment by feanz** [comment]
new release fixes issue
